name: book_store_reader
description: A book store and reading application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  cached_network_image: ^3.2.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.2
  get_it: ^7.6.0
  injectable: ^2.3.0
  json_annotation: ^4.8.1
  google_fonts: ^6.1.0
  flutter_tts: ^3.8.5
  share_plus: ^7.2.1
  uuid: ^4.2.2
  fl_chart: ^0.65.0
  audioplayers: ^5.2.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/sample_story.mp3 